### ISSUE TITLE
Language Selection Bug

### ISSUE THREAD

**Issue by AAyar94** [harunuyan/LoLGuide-Stats#1]
At the fırsat time app launch :
If User just continue without open spinner , app working with Turkish Language but spinner default selection is actually Czech Language
 ![Screenshot_20230731-072318_LoL Rehber.png](https://github.com/harunuyan/LoLGuide/assets/79112917/4bc8e5bc-7506-4260-932a-4fe5e0ef205c)

**Comment by harunuyan** [comment]
✓
